[lint]
rules = [
  "MD001",
  "MD002",
  "MD003",
  "MD004",
  "MD005",
  "MD006",
  "MD007",
  "MD009",
  "MD010",
  "MD012",
  "MD013",
  "MD014",
  "MD018",
  "MD019",
  "MD020",
  "MD021",
  "MD022",
  "MD023",
  "MD024",
  "MD025",
  "MD026",
  "MD027",
  "MD028",
  "MD029",
  "MD030",
  "MD031",
  "MD032",
  "MD033",
  "MD034",
  "MD035",
  "MD036",
  "MD037",
  "MD038",
  "MD039",
  "MD040",
  # Always fails with front matter
  # "MD041",
  "MD046",
  "MD047",
]
# Always fails with front matter
[lint.md002]
level = 2

# Fails on nested headings
[lint.md024]
# plugins.no-duplicate-header.enabled = false

[lint.md013]
line-length = 180
# plugins.line-length.code_block_line_length = 180
