default_language_version:
  python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: .*drawio$
  - id: mixed-line-ending
    args: [--fix, lf]
  - id: check-yaml
    args: [--allow-multiple-documents]
    additional_dependencies: [ruamel.yaml]
  - id: check-toml
  - id: check-json
  - id: pretty-format-json
    args: [--autofix]
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-vcs-permalinks
  - id: debug-statements
  - id: detect-private-key
  - id: forbid-new-submodules

- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.12
  hooks:
  - id: pymarkdown
    args: [--config, .pymarkdown.json, scan]
    additional_dependencies: [wcwidth]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.24.0
  hooks:
  - id: check-renovate
    additional_dependencies: [json5]
  - id: check-github-actions
