name: CI

on:
  push:
  pull_request:
  # For some dumb reason the PRs opened don't trigger reliably
  workflow_run:
    workflows:
    - Update packages
    types:
    - completed

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main
    - name: Test nix environment
      run: nix develop
    - name: Test website
      run: nix develop --command bash -c "zola build"
